### ISSUE TITLE
Generation of Integers in a range

### ISSUE THREAD

**Issue by alexcinergy** [vyznev/ISAAC-PHP#1]
Hello!

Is it possible to generate integers in a specific range with this algorithm? What's the best practise for it?

**Comment by vyznev** [comment]
As a quick answer, there is no built-in support in this ISAAC implementation for uniformly sampling integers from a given range, as it is mostly intended for interoperability with code using ISAAC as a stream cipher, for which you only need a stream of random bits. However, any generic algorithm for converting a stream of random bits into random integers in a range (such as those mentioned in [this Stack Overflow Q&A thread](https://stackoverflow.com/questions/6046918/how-to-generate-a-random-integer-in-the-range-0-n-from-a-stream-of-random-bits), which I just googled up) can be applied to the output of ISAAC.

ISAAC is a fairly fast (pseudo)random bit generator, so when choosing a conversion algorithm, simplicity and speed should generally be favored over frugality in the number of input bits consumed. For small ranges (say, 0 to *n*-1, where *n* < 2^16) it can be adequate to simply get a random 32-bit number *r* from ISAAC and reduce it modulo *n* (i.e. `r % n` in PHP code). The result will be slightly biased if *n* is not a power of two, but the bias will be on the order of one in 2^32 / *n*.

If that's too much bias for your needs, you can eliminate it using rejection sampling. The basic idea is that, before reducing *r* modulo *n*, you check whether `r < (1 << 32) % n` and, if it is, reject it and get another random 32-bit number *r* (repeating the check until you get an *r* that passes it). This way, the range of possible *r* values will be evenly divisible by *n*, and thus there will be no bias when it's reduced modulo *n*. 

One thing you should *not* need to do is handle power-of-two values of *n* specially. Unlike with bad old LCRNG algorithms, the low bits of ISAAC outputs aren't any less random than the high bits.

(All of the above assumes that the range you want starts at zero. If it does not, you should shift it so that it does. Also note that you may have sign issues and other problems, especially if using a 32-bit PHP build, since some of the outputs from ISAAC might be negative and a number like 2^32 may not even be representable — the expression `1 << 32` may simply evaluate to zero, which is *not* what we want here. I remember running into various problems like that when writing this ISAAC implementation, but I don't have the time to test them right now. Be careful and run some statistical tests on your code to make sure its outputs really are uniformly distributed.)

**Comment by alexcinergy** [comment]
Thanks a lot for the detailed response!

Are you free for commercial offers regarding this issue?
